version: '3.8'

services:
  web:
    container_name: game-container
    tty: true
    stdin_open: true
    environment:
      REACT_APP_API_HOST: http://localhost:4567
    build:
      context: ./web
    ports:
      - "3000:3000"
