version: '3.8'

services:
  web:
    container_name: typing-game-container
    tty: true
    stdin_open: true
    environment:
      REACT_APP_API_HOST: http://localhost
      REACT_APP_API_PORT: 4567
    build:
      context: ./web
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    container_name: typing-api-container
    tty: true
    stdin_open: true
    environment:
      HOST: db
      MYSQL_USER: game
      MYSQL_PASSWORD: game
      MYSQL_DATABASE: game
    ports:
      - "4567:4567"
    build:
      context: ./api
    restart: always
    depends_on:
      - db

  db:
    container_name: typing-mysql-container
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: game
      MYSQL_USER: game
      MYSQL_PASSWORD: game
      MYSQL_DATABASE: game
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
